name: Deploy Procargo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”§ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: ğŸ“¥ Install dependencies
        run: npm install --legacy-peer-deps

      - name: âš™ï¸ Build React project
        run: npm run build

      - name: ğŸš€ Deploy to CPanel via SSH
        uses: easingthemes/ssh-deploy@v2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-host: ${{ secrets.SSH_HOST }}
          remote-user: ${{ secrets.SSH_USERNAME }}
          source: 'build/'
          target: ${{ secrets.REMOTE_PATH }}
          args: "-avz --delete"
